# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-03-23 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportzilla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_count',
            field=models.IntegerField(default=0),
        ),
    ]
